# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: abstractplay-aiai
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '3'

plugins:
  - serverless-lift

provider:
  name: aws
  runtime: java21
  stage: ${opt:stage, 'dev'}
  region: us-east-1

constructs:
  aiai-queue:
    type: queue
    maxConcurrency: 5
    worker:
      handler: com.abstractplay.aiai.Handler
      timeout: 20
      layers:
        - !Ref AiaicliLambdaLayer

layers:
  aiaicli:
    package:
      artifact: lib/layers/aiai-layer.zip
    name: aiaicli-${self:provider.stage}
    description: "AiAi CLI binary" # optional, Description to publish to AWS
    compatibleRuntimes: # optional, a list of runtimes this layer is compatible with
      - java21
    compatibleArchitectures: # optional, a list of architectures this layer is compatible with
      - x86_64
    retain: false # optional, false by default. If true, layer versions are not deleted as new ones are created

package:
  artifact: target/aiai-invoke-1.0.0-beta.zip
  # patterns:
  #   - "!./**"
  #   - "target/*-shaded.jar"
